/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Riyan
 */
public class FrameIlustrator extends javax.swing.JFrame
{
    
    /*
        Frame made for showing ilustration of o2 n2 mixture in cylinder
        Designed by : Riyan S.I (riyansaputrai007@gmail.com)
        Keep it clean don't make modification without author's permissions
    */
    public String o2Stat,n2Stat; 
    public int O2percentage;
   
    public void paint(Graphics g)
    {
        /* Rules :
        To fill the cylinder with any color be sure its range
        parameter within 180-60.
        so you need this calculation method for fill the cylinder
        depending on oxygen percentage :
        (180-((O2percentage*120)/100))
        */
        
        /*Nitrogen Percentege*/
        g.setColor(Color.green);
        for (int i=(180-((O2percentage*120)/100));i>=60;i-=1)
        {
            g.fillOval(50, i, 100, 50);
        }
        
        /*Oxygen Percentage*/
        g.setColor(Color.blue);
        for (int i=180;i>=(180-((O2percentage*120)/100))-1;i-=1)
        {
            g.fillOval(50, i, 100, 50); 
            /*drawing separates of o2 and n2*/
            if (i==(180-((O2percentage*120)/100))-1)
            {
                g.setColor(Color.black);
                g.drawOval(50, i, 100, 50);
                g.setColor(Color.green);
                g.fillOval(50, i, 100, 50); 
            }
        } 
        
        /*drawing cylinder wireframe*/
        g.setColor(Color.black);
        g.drawOval(50, 60, 100, 50);
        g.drawLine(50,80,50,200);
        g.drawLine(150,80,150,200);
        g.drawOval(50, 180, 100, 50);
         
        /*drawing cylinder description*/
        /*oxygen*/
        g.setColor(Color.blue);
        g.drawRect(10, 280, 10, 20);
        g.fillRect(10, 280, 10, 20);
        /*nitrogen*/
        g.setColor(Color.green);
        g.drawRect(10, 305, 10, 20);
        g.fillRect(10, 305, 10, 20);
        /*text desc*/
        g.setColor(Color.black);
        g.drawString(o2Stat, 25, 295);
        g.drawString(n2Stat, 25, 320);
        
        
    }

    /**
     * Creates new form FrameIlustrator
     */
    public FrameIlustrator()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("02 N2 Mixture");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrameIlustrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrameIlustrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrameIlustrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrameIlustrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FrameIlustrator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
